#!/bin/sh

commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")

if ! echo "$commit_msg" | grep -qE '^(Added|Changed|Fixed|Removed)'; then
  echo "🛑 Commit message must start with 'Added', 'Changed', 'Removed' or 'Fixed'."
  exit 1
fi
echo "🟢 Commit message has the correct prefix."

if [ ${#commit_msg} -lt 20 ]; then
  echo "🛑 Commit message must be at least 20 characters long."
  exit 1
fi
echo "🟢 Commit message has the required minimum length."